<?php
Auth::requireAdmin();$admin=Auth::user();$adminTitle=$adminTitle??'Dashboard';$file=basename($_SERVER['PHP_SELF']);$flashes=pull_flashes();
$menu=[
 ['label'=>'Utama'],['file'=>'index.php','icon'=>'speedometer2','text'=>'Dashboard'],['file'=>'events.php','icon'=>'calendar-event','text'=>'Event'],
 ['label'=>'Master Data'],['file'=>'finalists.php','icon'=>'people','text'=>'Finalis'],['file'=>'winners.php','icon'=>'trophy','text'=>'Pemenang'],['file'=>'packages.php','icon'=>'box-seam','text'=>'Paket Voting'],
 ['label'=>'E-Voting'],['file'=>'transactions.php','icon'=>'credit-card','text'=>'Transaksi'],['file'=>'leaderboard.php','icon'=>'bar-chart','text'=>'Leaderboard'],
 ['label'=>'Konten'],['file'=>'content.php','icon'=>'layout-text-window','text'=>'Konten Website'],['file'=>'faqs.php','icon'=>'question-circle','text'=>'FAQ & Sponsor'],
 ['label'=>'Sistem'],['file'=>'users.php','icon'=>'person-gear','text'=>'Akun Superadmin'],['file'=>'audit-logs.php','icon'=>'journal-text','text'=>'Audit Log'],['file'=>'webhooks.php','icon'=>'broadcast-pin','text'=>'Webhook Xendit'],['file'=>'settings.php','icon'=>'gear','text'=>'Pengaturan']
];
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($adminTitle) ?> | Superadmin</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link href="<?= asset('css/admin.css') ?>" rel="stylesheet"></head><body>
<aside class="admin-sidebar" id="adminSidebar"><div class="admin-brand d-flex align-items-center gap-3"><img src="<?= asset('images/logo.svg') ?>"><div><strong class="d-block">Superadmin</strong><small class="text-white-50">Bujang Dayang Babel</small></div></div><nav class="admin-nav"><?php foreach($menu as $item):?><?php if(isset($item['label'])):?><div class="nav-label"><?= e($item['label']) ?></div><?php else:?><a class="<?= $file===$item['file']?'active':'' ?>" href="<?= url('admin/'.$item['file']) ?>"><i class="bi bi-<?= e($item['icon']) ?>"></i><?= e($item['text']) ?></a><?php endif;?><?php endforeach;?><a href="<?= url('index.php') ?>" target="_blank"><i class="bi bi-box-arrow-up-right"></i>Lihat Website</a><a href="<?= url('admin/logout.php') ?>"><i class="bi bi-box-arrow-left"></i>Keluar</a></nav></aside>
<div class="admin-main"><header class="admin-topbar"><div class="d-flex align-items-center gap-3"><button class="btn btn-light d-lg-none" onclick="document.getElementById('adminSidebar').classList.toggle('show')"><i class="bi bi-list"></i></button><div><h5 class="mb-0"><?= e($adminTitle) ?></h5><small class="text-secondary"><?= date('d/m/Y H:i') ?> WIB</small></div></div><div class="dropdown"><button class="btn btn-light rounded-pill dropdown-toggle" data-bs-toggle="dropdown"><i class="bi bi-person-circle me-2"></i><?= e($admin['name']??'Superadmin') ?></button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="<?= url('admin/users.php') ?>">Kelola Akun</a></li><li><a class="dropdown-item text-danger" href="<?= url('admin/logout.php') ?>">Keluar</a></li></ul></div></header><main class="admin-content"><?php foreach($flashes as $f):?><div class="alert alert-<?= e($f['type']) ?> alert-dismissible fade show"><?= e($f['message']) ?><button class="btn-close" data-bs-dismiss="alert"></button></div><?php endforeach;?>
